import "./globals.css";
import Provider from "@/app/providers/CredentialsProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-900">
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
